== 使用命令行界面

OpenShift附带了一个功能丰富的web控制台以及命令行工具为用户提供一个良好的界面将应用部署到平台。OpenShift工具是用Go语言编写的单个可执行文件，它适用于下列操作系统:

- Microsoft Windows
- macOS 10
- Linux

您的环境中可能已经有了OpenShift命令。您可以通过运行一个 `oc` 命令来验证它：

[source,bash,role=execute-1]
----
oc version --short
----

你应该看到以下(或类似的结果)：

[source,bash]
----
{{OC_VERSION}}
----

如果 `oc` 不存在，或者你有一个旧版本的OpenShift命令，请参照下一节内容来安装或更新OpenShift命令。否则，跳转到下一个实验。

== 在Linux环境下载并安装OpenShift命令

下载OpenShift 命令行工具的链接：{{DOWNLOAD_CLIENT_LIN64}}[Linux 64]

一旦下载了文件，它会是一个压缩归档文件，您需要提取其中的内容。建议将该文件保存到以下目录:

[source,bash]
----
~/openShift
----

打开一个终端窗口，并切换到您下载文件的目录。进入目录后，输入以下命令：

CAUTION: oc打包归档文件的名称可能会有所不同，有可能需要做相应调整。

[source,bash,role=copyandedit]
----
$tar zxvf oc-linux.tar.gz
----

tar.gz文件名需要替换为在上一步中下载的完整文件名。

现在你可以将OpenShift 命令行工具添加到环境的PATH变量。

[source,bash,role=execute-1]
----
export PATH=$PATH:~/openShift
----

此时，我们应该可以使用oc工具了。让我们来测试通过oc命令打印版本的输出：

[source,bash]
----
$ oc version
----

你应该看到以下(或类似的结果)：

[source,bash]
----
{{OC_VERSION}}
----

如果你得到一个错误消息，你没有正确更新你的路径。如果你需要帮助，请举手，老师会帮助你。

== 在Mac环境下载并安装OpenShift命令

下载OpenShift 命令行工具的链接：{{DOWNLOAD_CLIENT_MAC}}[Mac]

一旦下载了文件，它会是一个压缩归档文件，您需要提取其中的内容。建议将该文件保存到以下目录:

[source,bash]
----
~/openShift
----

打开一个终端窗口，并切换到您下载文件的目录。进入目录后，输入以下命令：

CAUTION: oc打包归档文件的名称可能会有所不同，有可能需要做相应调整。

[source,bash]
----
$ tar zxvf oc-macosx.tar.gz
----

tar.gz文件名需要替换为在上一步中下载的完整文件名。

现在你可以将OpenShift 命令行工具添加到环境的PATH变量。

[source,bash]
----
$ export PATH=$PATH:~/openShift
----

此时，我们应该可以使用oc工具了。让我们来测试通过oc命令打印版本的输出：

[source,bash]
----
$ oc version
----

你应该看到以下(或类似的结果)：

[source,bash]
----
{{OC_VERSION}}
----

如果你得到一个错误消息，你没有正确更新你的路径。如果你需要帮助，请举手，老师会帮助你。


== Tab键补全 

OpenShift命令行工具支持在流行的zsh和bash shell中使用制表符补全功能。这适合使用Linux或OS X的用户的需求。如果您使用Microsoft Windows，不用担心，我们将讨论一些在该操作系统上也可以使用tab键补全的方法。

=== 在Mac和Linux中的Tab键补全

如果你使用的是Mac操作系统，你需要确保你已经安装了 *bash-completion* 项目。这可以通过使用流行的brew系统来安装：

[source, bash]
----
$ brew install bash-completion
----

If you're on Linux, ensure you have *bash-completion* installed using your package manager (dnf, yum apt-get,...)如果你在Linux上，确保你已经使用包管理器(dnf, yum apt-get 等)安装了 *bash-completion* 。

一旦 *bash-completion* 包在您的机器中可用，要在shell中启用tab补全，您可以从终端简单地输入以下命令：

[source, bash]
----
$ oc completion bash >> oc_completion.sh
$ source oc_completion.sh
----

或者，您也可以将其添加到.bashrc文件中。

如果使用的是zsh，可以执行如下命令:

[source, bash]
----
$ source <(oc completion zsh)
----

或者，您也可以将其添加到.zshrc文件中。

=== 在Windows中的Tab键补全

对于Windows用户来说，事情就变得有点棘手了。当然，您可以在Windows上使用Linux子系统，但是您可能想要考虑使用babun和cmder的组合。要获得完整的说明列表，你可以查看以下博客文章:

-  https://blog.openshift.com/openshift-3-tab-completion-for-windows/[https://blog.openshift.com/openshift-3-tab-completion-for-windows/]

== 使用代理
有可能你是通过公司代理访问互联网的。在这种情况下，您需要设置让oc命令行工作的一些附加环境变量。

**Windows:**
按照上一节的说明在Windows上设置环境变量。你需要的变量设置有:

CAUTION: 将以下代理服务器的参数替换为您的环境/计算机的代理服务器地址

[source,bash]
----
https_proxy=http://proxy-server.mycorp.com:3128/
HTTPS_PROXY=http://proxy-server.mycorp.com:3128/
----

**macOS:**

CAUTION: 将以下代理服务器的参数替换为您的环境/计算机的代理服务器地址

[source,bash]
----
$ export https_proxy=http://proxy-server.mycorp.com:3128/
$ export HTTPS_PROXY=http://proxy-server.mycorp.com:3128/
----

**Linux:**

CAUTION: 将以下代理服务器的参数替换为您的环境/计算机的代理服务器地址

[source,bash]
----
$ export https_proxy=http://proxy-server.mycorp.com:3128/
$ export HTTPS_PROXY=http://proxy-server.mycorp.com:3128/
----

[NOTE]
====
如果代理有用户安全鉴权，请确保以下URL样式中设置了适当的值:

export https_proxy=http://USERNAME:PASSOWRD@proxy-server.mycorp.com:3128/

__Special Characters__: 如果您的密码包含特殊字符，您必须将其替换为ASCII码，例如必须将 @ 替换成 %40，即 p@ssword = p%40ssword。
====
