通过这个链接可以访问本次workshop使用的开源基础框架项目: https://github.com/openshift-homeroom[Homeroom]，这是一个交互式的培训环境，你无需在本地机器上安装任何东西，就可以在网页浏览器中开始实验。

Homeroom仪表板提供了对workshop内容的一个或多个访问终端。

交互式shell托管在OpenShift内部运行的容器中。您需要的所有特殊命令行程序都已经预先安装。

在进行workshop实验内容操作时，您需要在终端中运行的命令将以下面的形式显示:

[source,text,role=execute-1]
----
date
----

这个命令右边会出现一个play符号 +++<span class="fas fa-play-circle"></span>+++ ， 这表示您不需要自己在终端手工输入命令。只要简单单击命令上的任何地方，它将在终端中为您自动运行。

如果您还没点击的话，尝试点击上面的命令试试。

使用这种方法可以节省时间，避免错误。

通常该命令会在顶部的终端中运行，但在某些情况下，它将在底部终端中运行。您不必担心这一点，单击时命令将在它需要的地方运行。

尝试点击下面的命令，它应该会进入底部的终端。

[source,text,role=execute-2]
----
sleep 3600
----

如果你遇到一个显示 `<ctrl-c>` 的命令块，这将以特殊的方式处理:

[source,text,role=execute-2]
----
<ctrl-c>
----

点击这个命令块，你会看到在终端中运行的命令收到一个中断。您也可以直接在终端中使用 `<ctrl-c>` 。

有时，您可能需要复制值并将其粘贴到终端或其他web页面，而不是运行命令。 这将使用复制符号来表示 +++<span class="fas fa-copy"></span>+++。

[source,text,role=copy]
----
{{username}}
----

在这种情况下，单击显示的值将把它复制到系统剪贴板，以便粘贴到workshop手册指引您的任何位置。

通常workshop手册显示正确的命令或值，比如您的用户名或您正在使用的项目名称等等。这是因为您使用的是workshop内容的个性化版本。

如果在复制值时，需要在使用之前先编辑它，这将使用用户编辑符号来表示 +++<span class="fas fa-user-edit"></span>+++ 。

[source,text,role=copy-and-edit]
----
change-this-to-your-username
----

单击显示的值将再次将其复制到系统剪贴板，然后您可以将其粘贴到所需的位置，然后按照手册指示进行必要的更改后再在实验中使用。

如何将值粘贴到终端中取决于所使用的操作系统和浏览器。对于macOS，您应该能够使用 `<command-v>` 。在Linux和Windows上，可以用  `<ctrl-v>` 或 `<ctrl-shift-v>`。

如果在任何时候出现故障，由于网络问题workshop的内容不能正常显示，报出错误或者显示空白页面时，请点击终端右上角图标的下拉菜单选择“Reload Workshop”。该菜单项将重新加载workshop的内容，并定位到相同的页面。

同样，如果终端停止工作或显示为关闭，从下拉菜单中选择“Reload Terminal”。

不要使用浏览器的功能来重新加载整个浏览器页面，因为您将失去Workshop实验的进度。此外，不要使用“Restart Session”菜单项，除非特别需要，否则你会丢掉所有的实验工作进展。

如果您有任何使用重新加载菜单项不能解决的问题，请咨询workshop讲师。
