== 从 S2I 继续前行
正如您之前看到的，S2I是一种从源代码到容器的很好的方法，但是对于日常快速迭代开发来说，这个过程有点太慢了。例如，如果你想改变一些CSS或改变一个类中的方法，你不想经历完整的git提交和构建周期。在这个实验中，我们将向您展示一种更有效的快速迭代方法。而且在这里，我们还将向您展示如何调试您的代码。

现在我们建立了MLB parks服务，让我们继续做一些快速更改。

== 使用二进制部署快速迭代代码更改

OpenShift命令行可以在本地机器上执行部署。在本例中，我们将使用S2I，但是我们将告诉OpenShift从本地机器中获取war文件并将其打包到镜像中。

使用这种开发模式可以让我们在本地机器上进行快速构建(得益于本地缓存和我们机器上所有的算力)，然后迅速发送war文件。

NOTE: 您还可以使用此模式将工作目录实际发送到S2I构建器，让它在OpenShift进行Maven构建。使用本地目录将使您不必在本机使用Maven或任何Java工具链也不需要git push提交。 请参阅 https://{{DOCS_URL}}/dev_guide/dev_tutorials/binary_builds.html[官方文档]


== 练习：使用二进制部署

=== Clone 代码
第一步是从GitHub克隆MLB源代码到你的workshop环境：

[source,bash,role=execute-1]
----
git clone https://github.com/openshift-roadshow/mlbparks.git
----

NOTE: 我们在这里的截图指南中使用Intellij，但是不管你的工具链如何，这都应该是有效的。JBoss Developer Studio和JBoss Developer Tools已经内置了功能，使得这种无缝连接从IDE中就可以实现。

=== 设置 war 文件的构建
如果您的机器上已经全部设置了Maven，那么您就可以 `cd` 进入 `mlbparks` 目录并运行 `mvn package`


[source,bash,role=execute-1]
----
cd mlbparks
mvn package
----

请注意日志输出显示的 ROOT.war 所在位置。我们以后还需要那个目录。


=== 调整代码
是时候修改源代码了！我们定位到 `src/main/java/com/openshift/evg/roadshow/rest/BackendController.java`。然后用 `vi` 或 `nano` 来编辑它。

这是提供服务基本信息的REST端点，可以通过以下地址访问：

[source,bash,role=copypaste]
----
http://mlbparks-{{ project_namespace  }}.{{cluster_subdomain}}/ws/info/
----

请更改第23行，在“MLB Parks”前面添加一个 _AMAZING_ ，看起来像这样:

[source,java]
----
return new Backend("mlbparks", "AMAZING MLB Parks", new Coordinates("39.82", "-98.57"), 5);
----

不要忘记保存文件并再次运行 `mvn package` ：

[source,bash,role=execute-1]
----
cd /opt/app-root/src/mlbparks
mvn package
----

=== 进行二进制构建

好了，我们已经构建了war文件，是时候开始使用它进行构建了。

如果您用Maven构建好了war:

[source,bash,role=execute-1]
----
oc start-build bc/mlbparks --from-file=target/ROOT.war --follow
----

NOTE: --follow是可选参数，如果您想在终端中跟踪构建输出。

使用标签和重新创建部署策略，一旦新的部署完成，地图名称将被更新。在重新部署策略下，我们在进行新部署之前首先清理Pod。当pod被清理掉时，parksmap服务会将MLBParks地图从应用层中移除。当它回来时，应用层会自动添加我们的新标题Pod。如果是滚动部署就不会发生这种情况，因为在清理旧的Pod之前，滚动调度的新版本的Pod已经准备好了。滚动策略支持零停机部署。

您可以在拓扑视图中跟踪部署的进展，当部署完成时，您将在以下位置看到新内容：

[source,bash,role=copypaste]
----
http://mlbparks-{{ project_namespace  }}.{{cluster_subdomain}}/ws/info/
----

现在您已经了解了如何加快构建和部署过程。
